import { Theme } from "../theme.slint";

export component SearchBar inherits Rectangle {
    in property <string> placeholder-text: "Search apps files settings...";
    out property <string> text: input.text;
    callback edited(string);
    callback accepted(string);
    forward-focus: input;

    height: 36px;
    background: Theme.background.with-alpha(0.2);
    border-width: 1px;
    border-color: Theme.color7.with-alpha(0.65);
    clip: true;

    HorizontalLayout {
        padding-left: 12px;
        padding-right: 12px;
        spacing: 8px;
        alignment: start;

        Text {
            text: "\u{f002} ";
            font-family: "Monocraft";
            vertical-alignment: center;
            color: Theme.color7.with-alpha(0.65);
            font-size: 14px;
        }

        Rectangle {
            width: 100%;
            height: 100%;
            Text {
                text: root.placeholder-text;
                font-family: "Monocraft";
                visible: input.text == "";
                color: Theme.color7.with-alpha(0.65);
                width: 100%;
                horizontal-alignment: left;
                vertical-alignment: center;
                font-size: 13px;
            }
            input := TextInput {
                width: 100%;
                height: 100%;
                color: Theme.color4;
                font-size: 14px;
                vertical-alignment: center;
                single-line: true;
                edited => { root.edited(root.text); }
                accepted => { root.accepted(root.text); }
            }
        }
    }
}
