import { Theme } from "../theme.slint";

export component SearchBar inherits Rectangle {
    in property <string> placeholder-text: "Search...";

    callback edited(string);
    callback accepted(string);
    callback focus-appgrid();
    callback focus-input();
    forward-focus: input;

    height: 36px;
    background: Theme.background.with-alpha(0.2);
    border-width: 1px;
    border-color: Theme.color7.with-alpha(0.65);
    clip: true;

    HorizontalLayout {
        padding-left: 12px;
        padding-right: 12px;
        spacing: 8px;
        alignment: start;

        Text {
            text: "\u{f002} ";
            font-family: "Monocraft";
            vertical-alignment: center;
            color: Theme.color7.with-alpha(0.65);
            font-size: 14px;
        }

        Rectangle {
            width: 100%;
            height: 100%;

            Text {
                text: root.placeholder-text;
                font-family: "Monocraft";
                visible: input.text == "";
                color: Theme.color7.with-alpha(0.65);
                width: 100%;
                horizontal-alignment: left;
                vertical-alignment: center;
                font-size: 13px;
            }
            input := TextInput {
                width: 100%;
                height: 100%;
                color: Theme.color4;
                font-size: 14px;
                vertical-alignment: center;
                single-line: true;
                edited => { root.edited(input.text); }
                accepted => { root.accepted(input.text); }
                key-pressed(event) => {
                    if event.text == Key.DownArrow {
                        root.focus-appgrid();
                        accept
                    } else if event.text == Key.Return || event.text == "\u{000D}" || event.text == "\u{000A}" {
                        root.accepted(input.text);
                        accept
                    }
                    reject
                }
            }
        }
    }

    focus-input() => {
        input.focus();
    }
}
